version: '3.8'

services:
  adapter:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GHL_CLIENT_ID=${GHL_CLIENT_ID}
      - GHL_CLIENT_SECRET=${GHL_CLIENT_SECRET}
      - GHL_CONVERSATION_PROVIDER_ID=${GHL_CONVERSATION_PROVIDER_ID}
      - APP_URL=${APP_URL}
      - GHL_SHARED_SECRET=${GHL_SHARED_SECRET}
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=adapter
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
